name: CI-Security-Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  security:
    name: SAST + SCA
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # -------------------- SAST: Bandit --------------------
      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit SAST Scan
        run: |
          bandit -r . -f json -o bandit.json --exit-zero

      - name: Upload Bandit Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-sast-report
          path: bandit.json
          retention-days: 30

      # -------------------- SCA: Snyk --------------------
      - name: Run Snyk SCA Scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --json-file-output=snyk-report.json --fail-on=all
        continue-on-error: true

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sca-report
          path: snyk-report.json
          retention-days: 30

      # -------------------- SCA: Safety --------------------
      - name: Run Safety SCA Scan
        run: |
          pip install safety
          safety check --full-report --json > safety_report.json
        continue-on-error: true

      - name: Upload Safety Report
        uses: actions/upload-artifact@v4
        with:
          name: safety-sca-report
          path: safety_report.json