name: CI-Security-Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  security:
    name: SAST + SCA
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # -------------------- SAST: Bandit --------------------
      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit SAST Scan and generate HTML
        run: |
          bandit -r . -f html -o bandit-report.html --exit-zero

      - name: Upload Bandit HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-html-report
          path: bandit-report.html
          retention-days: 30

      # -------------------- SCA: Snyk --------------------
      - name: Run Snyk SCA Scan to JSON
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --json-file-output=snyk-report.json
        continue-on-error: true

      - name: Setup Node.js for Snyk HTML converter
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Convert Snyk JSON to HTML
        run: |
          npx snyk-to-html@latest -i snyk-report.json -o snyk-report.html
        continue-on-error: true

      - name: Upload Snyk HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-html-report
          path: snyk-report.html
          retention-days: 30

      # -------------------- SCA: Safety --------------------
      - name: Run Safety SCA Scan and generate HTML
        run: |
          pip install safety
          safety check --html safety-report.html
        continue-on-error: true

      - name: Upload Safety HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: safety-html-report
          path: safety-report.html
          retention-days: 30