name: CI-Security-Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
  workflow_dispatch:

jobs:
  security:
    name: SAST + SCA
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Upgrade pip + install prod deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # ---------------- Установка сканеров ----------------
    - name: Install security tooling (Bandit JSON + Safety + SARIF converter)
      run: |
        pip install "bandit>=1.7.7" safety bandit-sarif-formatter
        python -c "import bandit, sys; print('Bandit version:', bandit.__version__)"
        bandit --version

    # -------------------- SAST (Bandit) --------------------
    - name: Run Bandit SAST scan (JSON output)
      run: |
        bandit -r . -f json -o bandit.json

    - name: Convert Bandit JSON to SARIF
      run: |
        bandit-sarif-formatter bandit.json > bandit.sarif

    - name: Upload Bandit SARIF to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: bandit.sarif

    # -------------------- SCA (Safety) --------------------
    - name: Run Safety dependency scan
      id: safety
      run: |
        safety check --full-report \
                     --output text \
                     --fail-on high,critical \
                     > safety_report.txt

    - name: Upload Safety report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: safety-report
        path: safety_report.txt